version: 0.9.2.{build}

os:
- Windows Server 2012 R2

shallow_clone: true

environment:
  LR_EXTERNAL: c:\external

  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"
  - LUA: "lua 5.4"

platform:
  - x64
  - x86
  - mingw

cache:
  - c:\hererocks -> appveyor.yml
  - c:\external -> appveyor.yml

clone_script:
  - ps: >-
      if ( -not $env:appveyor_pull_request_number ) {
        git clone -q --branch=$env:appveyor_repo_branch https://github.com/$env:appveyor_repo_name.git $env:appveyor_build_folder
        git checkout -qf $env:appveyor_repo_commit
        git submodule update -q --init --recursive
      } else {
        git clone -q https://github.com/$env:appveyor_repo_name.git $env:appveyor_build_folder
        git fetch -q origin +refs/pull/$env:appveyor_pull_request_number/merge:
        git checkout -qf FETCH_HEAD
        git submodule update -q --init --recursive
      }

install:
  - set PATH=C:\Python27\Scripts;%LR_EXTERNAL%;%PATH%
  - if /I "%platform%"=="x86" set HR_TARGET=vs_32
  - if /I "%platform%"=="x64" set HR_TARGET=vs_64
  - if /I "%platform%"=="mingw" set HR_TARGET=mingw
  - if /I "%platform%"=="mingw" set PATH=C:\MinGW\bin;%PATH%
  - if not exist "%LR_EXTERNAL%" (
      mkdir "%LR_EXTERNAL%" &&
      mkdir "%LR_EXTERNAL%\lib" &&
      mkdir "%LR_EXTERNAL%\include"
    )
  - if not exist c:\hererocks (
      pip install hererocks &&
      hererocks c:\hererocks --%LUA% --target %HR_TARGET% -rlatest
    )
  - call c:\hererocks\bin\activate

before_build:
  # external deps

build_script:
  - luarocks make lua-http-parser-2.7-1.rockspec

before_test:
  # test deps
  - luarocks show luacov-coveralls >nul 2>&1 || luarocks install luacov-coveralls
  - luarocks show luasocket        >nul 2>&1 || luarocks install luasocket

test_script:
  - lua test.lua
  - lua bench.lua
